# Generated by Django 4.1 on 2022-10-12 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cote',
            name='strength',
            field=models.CharField(default='anything', max_length=200),
        ),
        migrations.AddField(
            model_name='cote',
            name='weak',
            field=models.CharField(default='anything', max_length=200),
        ),
    ]
